on:
  push:
    branches:
      - master
name: Publish olzimmerberg.ch
jobs:
  deploy-prod:
    name: Deploy to olzimmerberg.ch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build deployment
      run: ./build-deployment.sh
    - name: Deploy over SFTP
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        METHOD: sftp
        FTP_SERVER: lx7.hoststar.hosting
        PORT: 5544
        FTP_USERNAME: deploy.olzimmerberg.ch
        FTP_PASSWORD: ${{ secrets.PROD_FTP_PASSWORD }}
        ARGS: --parallel=4 --delete --verbose
        # --delete arg will delete files on the server if you've deleted them in git
        LOCAL_DIR: ./deploy
        REMOTE_DIR: .
